[package]
name = "crypto"
version = "0.1.0"
authors = ["luozijun <luozijun.assistant@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log         = "0.4"
subtle      = "2.2"
byteorder   = "1.3"
# packed_simd = "0.3"
# num-bigint  = "0.3"
# x25519-dalek  = "0.6"
# ed25519-dalek = "1.0.0-pre.3"

[dev-dependencies]
hex = "0.4"
# rand       = "0.7"
env_logger = { version = "0.7", default-features = false, features = ["termcolor", "atty", "humantime"] }

[features]
default = [ ]


[package.metadata.docs.rs]
all-features = true
# rustdoc-args = ["--cfg", "docsrs"]

# https://doc.rust-lang.org/cargo/reference/profiles.html#release
[profile.release]
opt-level = 3               # Use slightly better optimizations.
debug = false
debug-assertions = false
overflow-checks = false
lto = "fat"
panic = 'unwind'
incremental = false
codegen-units = 1

[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = "fat"
incremental = false
codegen-units = 1
rpath = false