
# env RUSTFLAGS="--print native-static-libs -C target-cpu=native -C target-feature=+aes,+sse,+sse4.1,+sse4.2,+avx,+avx2,+sha" cargo bench

[target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))']
rustflags = [
    "--print", "native-static-libs",
    "-C", "target-cpu=native",
    "-C", "target-feature=+aes,+sse,+sse4.1,+sse4.2,+avx,+avx2,+prefetchwt1,+pclmul,+fma4,+fma,+bmi2,+bmi,+adx,+prefer-256-bit,+prefer-128-bit",
]

[target.'cfg(target_arch = "arm")']
rustflags = [
    "--print", "native-static-libs",
    "-C", "target-cpu=native",
]

[target.'cfg(target_arch = "aarch64")']
rustflags = [
    "--print", "native-static-libs",
    "-C", "target-cpu=native",
    "-C", "target-feature=+aes,+crypto,+neon,+sha",
]
